version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - DB_USER
      - DB_PASSWORD
      - DB_DATABASE_NAME
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: